services:
  - type: web
    name: strapi-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: APP_KEYS
        value: "lwoh8gra6j,31lgna6sg0e,0pwt6myif8wh"
      - key: API_TOKEN_SALT
        value: 4i0cnhf7y6s
      - key: ADMIN_JWT_SECRET
        value: bpdu1i0hnle
      - key: TRANSFER_TOKEN_SALT
        value: eycfqg7e15s
      - key: JWT_SECRET
        value: 6lyau8i08m
      - key: ENCRYPTION_KEY
        value: 1ig48zy8svq
    autoDeploy: true
